apiVersion: v1
kind: Service
metadata:
  name: image-runtime-scanner-service
  namespace: cloudanix
spec:
  type: ClusterIP
  selector:
    app: image-runtime-scanner-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
